Added TCI git sample for Odata using SAP S4 Hana connector
TIBCOSoftware/tci-flogo pull request #207
Opened 2024-09-24 10:44 UTC by kramawat-tibco

2024-09-25 10:30 UTC, swagupta requested changes

2024-09-25 10:30 UTC, swagupta commented on samples/app-dev/Connectors/Miscellaneous/ODataS4hana/readme.md
> +![Sample Response](../../../import-screenshots/ODataS4Hana/47.png)
there are too many screenshots... you can remove this one

2024-09-25 10:30 UTC, swagupta commented on samples/app-dev/Connectors/Miscellaneous/ODataS4hana/readme.md
> +![Sample Response](../../../import-screenshots/ODataS4Hana/48.png)
remove this also and check if we remove some more which are not needed... too many screenshots make sample unreadable.

2024-09-25 10:30 UTC, swagupta commented on samples/app-dev/Connectors/Miscellaneous/ODataS4hana/readme.md
> +![Create an app](../../../import-screenshots/ODataS4Hana/60.png)
you can reuse common screenshots from import-screenshots parent directory
check for other common screenshots as well like for flow tester

2024-09-26 05:35 UTC, vinsharm-tibco commented on samples/app-dev/Connectors/Miscellaneous/ODataS4hana/readme.md
> +1. Ensure that SAP S4 Hana services are up and running
Please add one more pre-requisite
Make sure that user have correct Root URL of OData service (i.e., SAP S4 HANA)

2024-09-26 05:44 UTC, vinsharm-tibco commented on samples/app-dev/Connectors/Miscellaneous/ODataS4hana/readme.md
> +Authorization type OAuth2
You can remove this along with screenshot as this Authorization type is covered in Dataverse.

2024-09-26 05:44 UTC, vinsharm-tibco commented on samples/app-dev/Connectors/Miscellaneous/ODataS4hana/readme.md
> +Authorization type None
Remove this as it is not required.

2024-09-26 05:44 UTC, vinsharm-tibco commented on samples/app-dev/Connectors/Miscellaneous/ODataS4hana/readme.md
> +* If you see test connection failed for On-cloud connection in connection tab, then check Flogo DB Services is enabled or not and your public ip and TCI environment NAT ips are whitelisted or not.
Remove this, its for DBService and not for OData

2024-09-26 05:44 UTC, vinsharm-tibco commented on samples/app-dev/Connectors/Miscellaneous/ODataS4hana/readme.md
> +* If you see test connection failed for On-premies connection in connection tab, then check Flogo DB Services is enabled or not and tibagent is started for oracle database server or not.
Remove this, its for DBService and not for OData

2024-09-26 05:44 UTC, vinsharm-tibco commented on samples/app-dev/Connectors/Miscellaneous/ODataS4hana/readme.md
> +* While executing on-premise connection app from endpoint, make sure that accesskey should be selected in Hybride connectivity option from Environment controls tab and executing from flow tester make
Remove this, its for DBService and not for OData

2024-09-26 05:44 UTC, vinsharm-tibco commented on samples/app-dev/Connectors/Miscellaneous/ODataS4hana/readme.md
> +* If you are not able to fech the tables or table coloumns while typing a query, then make sure your connection should be establish successfully.
Remove this, its for DBService and not for OData

2024-09-26 05:44 UTC, vinsharm-tibco commented on samples/app-dev/Connectors/Miscellaneous/ODataS4hana/readme.md
> +* If you do not see the Endpoint enabled, make sure your apps is in Running status.
Add one more point in this 
If you see test connection failed in connection tab, then check if Username and Password are correct

2024-10-29 09:04 UTC, merged